# -*- mode: ruby -*-

source 'https://rubygems.org'


# base rails install
gem 'rails', '3.1.3'
gem 'pg'
gem 'silent-postgres'
gem 'active_reload'

# rails 3.1 asset pipeline
group :assets do
  gem 'sass-rails',   '~> 3.1.4'
  gem 'coffee-rails', '~> 3.1.1'
  gem 'uglifier',     '>= 1.0.3'
  # needed for building assets?
  gem 'sqlite3'
end
gem 'json'
gem 'jquery-rails'  #, '1.0.17'

# high-level structural tools used everywhere
gem 'haml'
gem 'haml-rails'
gem 'coffee-filter'
gem 'squeel'
gem 'inherited_resources', '~> 1.3'

gem 'yard'
gem 'redcarpet'
gem 'github-markup'

# debugger
#gem 'ruby-debug19', :require => 'ruby-debug'

gem 'capistrano'
gem 'capistrano_colors'

group :console do
  gem 'awesome_print'
end

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end


