#!/bin/bash

# force old GTK apps
export GDK_USE_XFT=1
# force old QT apps
export QT_XFT=true

#source /usr/lib/ft-settings.sh default
#source /usr/lib/ft-settings.sh infinality

source /usr/lib/ft-settings.sh sharpened
# export INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE=45
# export INFINALITY_FT_GAMMA_CORRECTION="1000 110"
# export INFINALITY_FT_FRINGE_FILTER_STRENGTH=10
# export INFINALITY_FT_FILTER_PARAMS="11 22 38 22 11"


# export INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH=10
# export INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS=true
# export INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT=100
# export INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH=25
# export INFINALITY_FT_BRIGHTNESS=0
# export INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH=0
# export INFINALITY_FT_CONTRAST=0
# export INFINALITY_FT_FILTER_PARAMS="11 22 38 22 11"
# export INFINALITY_FT_FRINGE_FILTER_STRENGTH=25
# export INFINALITY_FT_GAMMA_CORRECTION="1000 120"
# export INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE=30
# export INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH=0
# export INFINALITY_FT_STEM_ALIGNMENT_STRENGTH=25
# export INFINALITY_FT_STEM_FITTING_STRENGTH=25
# export INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE=40
# export INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS=true
# export INFINALITY_FT_USE_VARIOUS_TWEAKS=true
# export INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH=5


#source /etc/env.d/99lcdfilter


# export INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH=10
# export INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS=true
# export INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT=100
# export INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH=25
# export INFINALITY_FT_BRIGHTNESS="0"
# export INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH=0
# export INFINALITY_FT_CONTRAST="0"
# export INFINALITY_FT_FILTER_PARAMS="11 22 38 22 11"
# export INFINALITY_FT_FRINGE_FILTER_STRENGTH=0
# export INFINALITY_FT_GAMMA_CORRECTION="0 100"
# export INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH=0
# export INFINALITY_FT_STEM_ALIGNMENT_STRENGTH=25
# export INFINALITY_FT_STEM_FITTING_STRENGTH=25
# export INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE=40
# export INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS=true
# export INFINALITY_FT_USE_VARIOUS_TWEAKS=true
# export INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH=5



# Local Variables:
# mode: sh
# sh-basic-offset: 4
# sh-shell: bash
# coding: unix
# End:
