#!/bin/bash

_ORIGENV_FF_ADDON_PYTHONPATH="${PYTHONPATH}"
_ORIGENV_FF_ADDON_PATH="${PATH}"

VIRTUAL_ENV="${HOME}/opt/firefox/addon-sdk-1.9"

CUDDLEFISH_ROOT="${VIRTUAL_ENV}"
PYTHONPATH="${VIRTUAL_ENV}/python-lib:${PYTHONPATH}"
PATH="${VIRTUAL_ENV}/bin:${PATH}"

export CUDDLEFISH_ROOT PYTHONPATH PATH

PROMPT_PREFIX="addon-sdk"

unloadenv_ff_addon() {
    PYTHONPATH="${_ORIGENV_FF_ADDON_PYTHONPATH}"
    PATH="${_ORIGENV_FF_ADDON_PATH}"
    export PATH PYTHONPATH

    unset CUDDLEFISH_ROOT PROMPT_PREFIX VIRTUAL_ENV
    unset _ORIGENV_FF_ADDON_PATH _ORIGENV_FF_ADDON_PYTHONPATH

    unset -f unloadenv_ff_addon
}


# Local Variables:
# mode: sh
# sh-basic-offset: 4
# sh-shell: bash
# coding: unix
# End:
